version: 2
jobs:
  dependency_cache:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Update NPM
          command: npm install npm@latest -g
      - run:
          name: Node Info
          command: node --version && npm --version
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  node-v14-latest:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Run Tests
          command: |
            sudo apt-get update
            sudo apt-get install -y libgbm-dev
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 14
            nvm alias default 14
            node --version && npm --version
            npm install
            npm run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: NPM Rebuild
          command: npm install
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Validate Commit Messages
          command: npm run ci:lint:commits
workflows:
  version: 2
  validate:
    jobs:
      - dependency_cache
      - analysis:
          requires:
            - dependency_cache
          filters:
            tags:
              only: /.*/
      - node-v14-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
